----------------------------------------------------------------------------
-- GoldenOrb: Hands Position Reset Modifier
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Log
local log = goldenorb_logging.log

-- Implementation

--- Zero out the position component
function reset_hands_position(state)
   log("reset_hands_position(%s)", state)

   if state.hud then
      state.hud.hands_position = vector()
   end

   return state
end
