----------------------------------------------------------------------------
-- GoldenOrb: Fire Point Offset Modifier
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Math
local EPSILON = goldenorb_math.EPSILON

--- Log
local log = goldenorb_logging.log

-- Constants

local OFFSET = vector():set(0, 0, EPSILON)

-- Implementation

--- Offset fire point slightly to prevent self-intersection
function offset_fire_point(state)
   log("offset_fire_point(%s)", state)

   if state.hud then
      state.hud.fire_point:add(OFFSET)
      state.hud.fire_point2:add(OFFSET)
   end

   return state
end
