----------------------------------------------------------------------------
-- GoldenOrb: Impure Actions
----------------------------------------------------------------------------
-- Covers any action that reads or writes state outside of GoldenOrb.
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

--- Inject the actor into the given state
function inject_actor(state)
   state.actor = db.actor
   return state
end

--- Set HUD adjustment
function hud_adjust_enable(state)
   hud_adjust.enabled(true)
   return state
end
