----------------------------------------------------------------------------
-- RoboDolg
----------------------------------------------------------------------------
-- 
-- Vector HUD for Anomaly
-- 
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Logging
local log = goldenorb_logging.log

-- Implementation

local cache = nil
function cache_state(state)
   cache = state
   return state
end

function draw_robodolg()
   log("draw_robodolg()")
   if cache then
      SendScriptCallback("robodolg_on_draw", cache)
   end
end

function on_game_start()
   log("robodolg.on_game_start")

   -- Declare our draw callback
   AddScriptCallback("robodolg_on_draw")

   -- Register with GoldenOrb's update callback
   goldenorb_main.ACTOR_ON_UPDATE:add_call(cache_state)
   AddUniqueCall(draw_robodolg)
end
