----------------------------------------------------------------------------
-- GoldenOrb: Table Utilities
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

---@param tbl table
---@param f fun(k: any, v: any): (any, any)
---@return table
function map(tbl, f)
   local out = {}
   for ka,va in pairs(tbl) do
      local kb,vb = f(ka, va)
      out[kb] = vb
   end
   return out
end

---@param tbl table
---@param f fun(k: any, v: any)
---@return nil
function foreach(tbl, f)
   for ka,va in pairs(tbl) do
      f(ka, va)
   end
end
