--- Returns whatever was passed to it
---@param ... any
---@return any
function id(...)
   return ...
end

--- Produce a function that threads an input through the given functions
---@param ... fun(any: any): any
---@return fun(any: any): any
function compose(...)
   local fs = {...}

   local acc = function(p)
      return p
   end

   for i=1,#fs do
      local old = acc
      acc = function(p)
         return fs[i](old(p))
      end
   end

   return acc
end

