----------------------------------------------------------------------------
-- RoboDolg: Enable Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens", "Prism"},
   cl_types = {"is_nil", "is_table"},
})

-- Implementation

C_ENABLE = Lens.where("enable", is_table)
C_NOT_ENABLE = Prism.where("enable", is_nil, is_table)
