----------------------------------------------------------------------------
-- RoboDolg: Enable Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

local Lens = cl_schedule.Lens
local Prism = cl_schedule.Prism
local is_nil = cl_schedule.is_nil
local is_table = cl_schedule.is_table

-- Implementation

C_ENABLE = Lens.where("enable", is_table)
C_NOT_ENABLE = Prism.where("enable", is_nil, is_table)
