----------------------------------------------------------------------------
-- GoldenOrb: Weapon Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports
local Lens = cl_schedule.Lens
local is_non_nil = cl_schedule.is_non_nil

-- Implementation

C_WEAPON = Lens.where("wpn", is_non_nil)
