----------------------------------------------------------------------------
-- GoldenOrb: Actor Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

local Lens = cl_schedule.Lens
local Prism = cl_schedule.Prism
local is_nil = cl_schedule.is_nil
local is_non_nil = cl_schedule.is_non_nil

-- Constants

C_ACTOR = Lens.where("actor", is_non_nil)
C_NOT_ACTOR = Prism.where("actor", is_nil, is_non_nil)
