----------------------------------------------------------------------------
-- GoldenOrb: Matrices Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Schedule
local Lens = _cl_schedule.Lens
local Prism = _cl_schedule.Prism
local is_nil = _cl_schedule.is_nil
local is_table = _cl_schedule.is_table

-- Implementation

C_MATRICES = Lens.where("matrices", is_table)
C_NOT_MATRICES = Prism.where("matrices", is_nil, is_table)
