----------------------------------------------------------------------------
-- GoldenOrb: Gimbals Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens"},
   cl_types = {"is_table", "is_nil"},
})

-- Implementation

C_GIMBALS = Lens.where("gimbals", is_table)
C_NOT_GIMBALS = Lens.where("gimbals", is_nil, is_table)
