----------------------------------------------------------------------------
-- GoldenOrb: Recoil Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Schedule
Lens = cl_schedule.Lens
Prism = cl_schedule.Prism
is_nil = cl_schedule.is_nil
is_non_nil = cl_schedule.is_non_nil
is_table = cl_schedule.is_table
is_matrix = cl_schedule.is_matrix

-- Implementation 

C_RECOIL = Lens.where("recoil", is_table)
C_NOT_RECOIL = Prism.where("recoil", is_nil, is_table)

C_ACTOR = Lens.where("actor", is_non_nil)
C_CAMERA = Lens.where("camera", is_non_nil)
C_HUD = Lens.where("hud", is_non_nil)
