----------------------------------------------------------------------------
-- GoldenOrb: Recoil Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens", "Prism"},
   cl_types = {"is_nil", "is_non_nil", "is_table", "is_matrix"},
})

-- Implementation 

C_RECOIL = Lens.where("recoil", is_table)
C_NOT_RECOIL = Prism.where("recoil", is_nil, is_table)

C_ACTOR = Lens.where("actor", is_non_nil)
C_CAMERA = Lens.where("camera", is_non_nil)
C_HUD = Lens.where("hud", is_non_nil)
