----------------------------------------------------------------------------
-- GoldenOrb: Gimbals Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

local Lens = cl_schedule.Lens
local is_table = cl_schedule.is_table
local is_nil = cl_schedule.is_nil

-- Implementation

C_GIMBALS = Lens.where("gimbals", is_table)
C_NOT_GIMBALS = Lens.where("gimbals", is_nil, is_table)
