----------------------------------------------------------------------------
-- GoldenOrb: Springs Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- Schedule
local Lens = cl_schedule.Lens
local Prism = cl_schedule.Prism
local is_nil = cl_schedule.is_nil
local is_table = cl_schedule.is_table

-- Implementation

C_SPRINGS = Lens.where("springs", is_table)
C_NOT_SPRINGS = Prism.where("springs", is_nil, is_table)
