----------------------------------------------------------------------------
-- GoldenOrb: Matrices Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens", "Prism"},
   cl_types = {"is_nil", "is_table"},
})

-- Implementation

C_MATRICES = Lens.where("matrices", is_table)
C_NOT_MATRICES = Prism.where("matrices", is_nil, is_table)
