----------------------------------------------------------------------------
-- GoldenOrb: Weapon Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens"},
   cl_types = {"is_non_nil"}
})

-- Implementation

C_WEAPON = Lens.where("wpn", is_non_nil)
