----------------------------------------------------------------------------
-- GoldenOrb: Springs Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens", "Prism"},
   cl_types = {"is_nil", "is_table"}
})

-- Implementation

C_SPRINGS = Lens.where("springs", is_table)
C_NOT_SPRINGS = Prism.where("springs", is_nil, is_table)
