----------------------------------------------------------------------------
-- GoldenOrb: Camera Components
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

cl_import(this, {
   cl_optics = {"Lens", "Prism"},
   cl_types = {"is_nil", "is_non_nil", "is_boolean"}
})

-- Implementation

C_CAMERA = Lens.where("camera", is_non_nil)
C_NOT_CAMERA = Prism.where("camera", is_nil, is_non_nil)

C_CAM_FLAG = Lens.where("_cam_custom_position_direction", is_boolean)
C_NOT_CAM_FLAG = Prism.where(
    "_cam_custom_position_direction", is_nil, is_boolean
)
