----------------------------------------------------------------------------
-- RoboDolg
----------------------------------------------------------------------------
-- 
-- Vector HUD for Anomaly
-- 
----------------------------------------------------------------------------
-- Implemented by Lhan
----------------------------------------------------------------------------

-- Imports

--- MCM Builder
local Tree = mcm_builder.Tree

--- RoboDolg Shapes
local reset = robodolg_shapes.reset

--- Logging
local log = robodolg_logging.log

-- State

tree = Tree.new("robodolg")

-- Implementation

function reset_pool()
   reset()
end

--- Entrypoint
---@return nil
function on_game_start()
   log("robodolg.on_game_start")

   RegisterScriptCallback("actor_on_update", reset_pool)
end

--- Build the MCM tree on load
---@return nil
function on_mcm_load()
   return tree:build()
end
